plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.5'
	id 'com.github.node-gradle.node' version '7.0.2'
}

group = 'com.lebedev'
version = '0.0.6-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-restclient'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	implementation 'io.jsonwebtoken:jjwt-gson:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	implementation "org.telegram:telegrambots-client:10.3.0"
    implementation "org.telegram:telegrambots-springboot-longpolling-starter:10.3.0"
    implementation group: 'redis.clients', name: 'jedis', version: '5.1.3'
	implementation 'org.postgresql:postgresql:42.7.3'

	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testRuntimeOnly 'com.h2database:h2'
}

node {
	download = false
	nodeProjectDir = file("${project.projectDir}/frontend")
}

tasks.register('buildReact', NpmTask) {
	dependsOn npmInstall
	workingDir = file("${project.projectDir}/frontend")
	args = ['run', 'build']
}

tasks.register('copyReactBuild', Copy) {
	dependsOn buildReact
	mustRunAfter resolveMainClassName, compileTestJava, jar, test
	from "${project.projectDir}/frontend/build"
	into "${project.layout.buildDirectory.get()}/resources/main/static"
}

processResources {
	filesMatching('application.properties') {
		expand(version: project.version)
	}
}

bootJar {
	dependsOn copyReactBuild
}

tasks.named('test') {
	useJUnitPlatform()
}
